version: "3.3"

services:
  thenextnothing:
    build: ./TheNextNothing
    command: python manage.py runserver 0.0.0.0:1337
    volumes:
      - ./TheNextNothing:/tnn/
    ports:
      - "1337:1337"
    restart: always
  nctimeabuse:
    build: ./NC_time_abuse
    command: python server.py
    volumes:
      - ./NC_time_abuse:/ncta/
    ports:
      - "8889:8889"
    restart: always
  tasks:
    build: ./Tasks
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - ./Tasks:/tsks/
    ports:
      - "8002:8002"
    restart: always
#  ds:
#    build: ./django-shop
#    command: python manage.py runserver 0.0.0.0:8003
#    volumes:
#      - ./django-shop:/ds/
#    ports:
#      - "8003:8003"
#    restart: always
