version: "3.3"

services:
  thenextnothing:
    build: ./TheNextNothing
    command: python manage.py runserver 0.0.0.0:1336
    volumes:
      - ./TheNextNothing:/tnn/
    ports:
      - "1336:1336"
    restart: always
  nctimeabuse:
    build: ./NC_time_abuse
    command: python server.py
    volumes:
      - ./NC_time_abuse:/ncta/
    ports:
      - "8889:8889"
    restart: always
  tasks:
    build: ./Tasks
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - ./Tasks:/tsks/
    ports:
      - "8002:8002"
    restart: always
  django:
    build: ./CVE_Django
    command: python manage.py runserver 0.0.0.0:83
    volumes:
      - ./CVE_Django:/code/
    ports:
      - "83:83"
    restart: always
  secret:
    build: ./SecretSociety
    volumes:
      - ./SecretSociety:/secret/
    ports:
      - "9990:9990"
    restart: always
